### ISSUE TITLE
How to get the raw video clips for ARGO1M

### ISSUE THREAD

**Issue by mortyzhou77** [Chiaraplizz/ARGO1M-What-can-a-cook#3]
Thank you for your work, and I already download the FFCV encoding files and csv, but I want to get the raw videos for ARGO1M, Do I need to download the whole Ego4D and extract the video from it with the uids?

**Comment by Chiaraplizz** [comment]
Hi! :-)

You can also select the ARGO1M videos you need to download with the flag `--video_uids` when you download the videos with `ego4d --output_directory="~/ego4d_data" --datasets full_scale annotations --metadata`. 





<br class="Apple-interchange-newline">

**Comment by mortyzhou77** [comment]
Thank u so much!
